[package]
name = "mimicaw-framework-macros"
version = "0.0.0" # never publish
publish = false
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
syn = "1"
quote = "1"
