[package]
name = "mimi"
version = "0.0.0"
publish = false
description = """
Minimal test harness that mimics libtest for asynchronous integration tests.
"""
license = "MIT OR Apache-2.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
futures-intrusive = "0.2"
structopt = "0.3"

[dev-dependencies]
anyhow = "1"
async-std = { version = "1", features = ["attributes"] }
tokio = { version = "0.2.0", features = [ "full" ] }
