[package]
name = "mimicaw"
version = "0.0.0"
publish = false
description = """
Minimal test harness that mimics libtest for asynchronous integration tests.
"""
license = "MIT OR Apache-2.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
edition = "2018"

[dependencies]
console = "0.9"
futures = "0.3"
getopts = "0.2"
indicatif = "0.13"
num-format = "0.4"
pin-project-lite = "0.1"

[dev-dependencies]
async-std = { version = "1", features = ["attributes"] }
futures-timer = "2"
tokio = { version = "0.2.0", features = [ "full" ] }
